# Generated by Django 5.0.6 on 2024-06-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='poll_name',
            field=models.CharField(default='name', max_length=128),
            preserve_default=False,
        ),
    ]
