# Generated by Django 5.0.6 on 2024-06-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pollanswer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='poll_name',
            new_name='question',
        ),
        migrations.AddField(
            model_name='poll',
            name='correct_option_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
